bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner.git
        branch: "1.0-beta-12"
    docker:
      base: "jenkins/jenkins:2.241-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.241"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "v0.2.2"


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# JavaScript GUI Lib: ACE Editor bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "ace-editor"
    source:
      version: "1.1"
# Static Analysis Utilities (Jenkins-Version: 1.625.1)
  - groupId: "org.jvnet.hudson.plugins"
    artifactId: "analysis-core"
    source:
      version: "1.96"
# Analysis Model API (Jenkins-Version: 2.204.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "8.1.3"
# OWASP Markup Formatter (Jenkins-Version: 2.121.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "2.0"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.10-2.0"
# Authentication Tokens API (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.3"
# Badge (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "badge"
    source:
      version: "1.8"
# Bootstrap 4 API (Jenkins-Version: 2.204.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap4-api"
    source:
      version: "4.5.0-1"
# bouncycastle API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.18"
# Branch API (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.5.6"
# Build Timeout (Jenkins-Version: 2.222.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.20"
# Folders (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.14"
# Cobertura (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.16"
# Code Coverage API (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "1.1.6"
# Configuration as Code (Jenkins-Version: 2.222)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1.41"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Credentials (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "2.3.9"
# Credentials Binding (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "1.23"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.204.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "1.10.21-2"
# Display URL API (Jenkins-Version: 2.89.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.3.2"
# Docker Commons (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "docker-commons"
    source:
      version: "1.16"
# Durable Task (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "1.34"
# ECharts API (Jenkins-Version: 2.204.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "4.7.0-4"
# Email Extension (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "email-ext"
    source:
      version: "2.69"
# FindBugs (Jenkins-Version: 1.625.1)
  - groupId: "org.jvnet.hudson.plugins"
    artifactId: "findbugs"
    source:
      version: "5.0.0"
# Font Awesome API (Jenkins-Version: 2.138.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "5.13.0-1"
# Forensics API (Jenkins-Version: 2.138.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "0.7.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "4.2.2"
# Git client (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "3.2.1"
# GIT server (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-server"
    source:
      version: "1.9"
# GitHub (Jenkins-Version: 2.60.3)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.30.0"
# GitHub API (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.114.2"
# GitHub Branch Source (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "2.8.2"
# Google OAuth Credentials (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "google-oauth-plugin"
    source:
      version: "1.0.0"
# Gradle (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "1.36"
# JavaScript GUI Lib: Handlebars bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "handlebars"
    source:
      version: "1.1.1"
# HTML Publisher (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.23"
# HTTP Request (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.8.26"
# InfluxDB (Jenkins-Version: 2.195)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "2.3"
# Jackson 2 API (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.11.0"
# JaCoCo (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.0.6"
# Javadoc (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "javadoc"
    source:
      version: "1.5"
# JavaScript GUI Lib: jQuery bundles (jQuery and jQuery UI) (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "jquery-detached"
    source:
      version: "1.2.1"
# JQuery3 API (Jenkins-Version: 2.204.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.5.1-1"
# JSch dependency (Jenkins-Version: 2.190.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jsch"
    source:
      version: "0.1.55.2"
# JUnit (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1.29"
# Kubernetes (Jenkins-Version: 2.222.4)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "1.26.1"
# Kubernetes Client API (Jenkins-Version: 2.204.6)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "4.9.2-2"
# Kubernetes Credentials (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.6.2"
# Kubernetes Credentials Provider (Jenkins-Version: 2.190.1)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "0.15"
# Lockable Resources (Jenkins-Version: 2.138.4)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "2.8"
# Mailer (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "1.32"
# Matrix Project (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "1.16"
# Maven Integration (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.main"
    artifactId: "maven-plugin"
    source:
      version: "3.6"
# JavaScript GUI Lib: Moment.js bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "momentjs"
    source:
      version: "1.1.1"
# OAuth Credentials (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "oauth-credentials"
    source:
      version: "0.4"
# OkHttp (Jenkins-Version: 2.164.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "3.12.12.2"
# Pipeline: Build Step (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "2.12"
# Pipeline: GitHub (Jenkins-Version: 2.128)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.5"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "1.0"
# Pipeline Graph Analysis (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-graph-analysis"
    source:
      version: "1.10"
# Pipeline: Input Step (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "2.11"
# Pipeline: Milestone Step (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "1.3.1"
# Pipeline: Model API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "1.7.0"
# Pipeline: Declarative (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "1.7.0"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "1.7.0"
# Pipeline: REST API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-rest-api"
    source:
      version: "2.13"
# Pipeline: Stage Step (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "2.3"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "1.7.0"
# Pipeline: Stage View (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-stage-view"
    source:
      version: "2.13"
# Pipeline Utility Steps (Jenkins-Version: 2.121.2)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.6.0"
# Plain Credentials (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "1.7"
# Plugin Utilities API (Jenkins-Version: 2.204.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "1.2.2"
# PMD (Jenkins-Version: 1.625.1)
  - groupId: "org.jvnet.hudson.plugins"
    artifactId: "pmd"
    source:
      version: "4.0.0"
# Popper.js API (Jenkins-Version: 2.138.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "popper-api"
    source:
      version: "1.16.0-6"
# Resource Disposer (Jenkins-Version: 2.54)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.14"
# SCM API (Jenkins-Version: 2.107.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "2.6.3"
# Script Security (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1.73"
# Snakeyaml API (Jenkins-Version: 2.204.6)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "1.26.4"
# SSH Credentials (Jenkins-Version: 2.190.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "1.18.1"
# Structs (Jenkins-Version: 2.107.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "1.20"
# Timestamper (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.11.3"
# Token Macro (Jenkins-Version: 2.121.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "2.12"
# Trilead API (Jenkins-Version: 2.184)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "1.0.8"
# Variant (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "1.3"
# Warnings (Jenkins-Version: 2.89.1)
  - groupId: "org.jvnet.hudson.plugins"
    artifactId: "warnings"
    source:
      version: "5.0.1"
# Warnings Next Generation (Jenkins-Version: 2.138.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "8.1.0"
# Pipeline (Jenkins-Version: 2.130)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "2.6"
# Pipeline: API (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "2.40"
# Pipeline: Basic Steps (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "2.20"
# Pipeline: Groovy (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "2.80"
# Pipeline: Shared Groovy Libraries (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps-global-lib"
    source:
      version: "2.16"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "2.35"
# Pipeline: Job (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "2.39"
# Pipeline: Multibranch (Jenkins-Version: 2.121.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "2.21"
# Pipeline: SCM Step (Jenkins-Version: 2.60)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "2.11"
# Pipeline: Step API (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "2.22"
# Pipeline: Supporting APIs (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "3.5"
# Workspace Cleanup (Jenkins-Version: 2.121)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.38"
##PLUGINS-END (do not remove!)
