bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        # Use fork until fixes are available in upstream.
        # We should check if the --waitOnExit parameter makes our fork obsolete. Will be contained after 1.0-beta-30.
        # git: https://github.com/jenkinsci/jenkinsfile-runner.git
        # branch: "1.0-beta-30"
        git: https://github.com/romanisb/jenkinsfile-runner.git
        branch: "stewardci"
        # git: https://github.com/SAP/stewardci-jenkinsfilerunner-image
        # branch: "jenkinsfile-runner--1.0-beta-30-steward-1"
    docker:
        # Last version which does not break due to "JEP-230: Convert modules to plugins"
        # https://github.com/jenkinsci/jep/tree/master/jep/230
        # Compiling JFR will fail due to missing versions in Jenkins parent bom
        # https://github.com/jenkinsci/jenkinsfile-runner/blob/main/setup/pom.xml#L42-L70
      base: "jenkins/jenkins:2.346.3-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.346.3"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "0.11.1"


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# JavaScript GUI Lib: ACE Editor bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "ace-editor"
    source:
      version: "1.1"
# Analysis Model API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "10.22.0"
# OWASP Markup Formatter (Jenkins-Version: 2.277.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "155.v795fb_8702324"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.13-138.v4e7d9a_7b_a_e61"
# Authentication Tokens API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.4"
# Bootstrap 5 API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap5-api"
    source:
      version: "5.2.1-3"
# bouncycastle API (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.27"
# Branch API (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.1071.v1a_188a_562481"
# Build Timeout (Jenkins-Version: 2.332.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.24"
# Caffeine API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "caffeine-api"
    source:
      version: "2.9.3-65.v6a_47d0f4d1fe"
# Checks API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "checks-api"
    source:
      version: "1.8.1"
# Folders (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.740.ve4f4ffa_dea_54"
# Cobertura (Jenkins-Version: 2.204.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.17"
# Code Coverage API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "3.4.1"
# commons-lang3 v3.x Jenkins API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-lang3-api"
    source:
      version: "3.12.0-36.vd97de6465d5b_"
# commons-text API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-text-api"
    source:
      version: "1.10.0-27.vb_fa_3896786a_7"
# Configuration as Code (Jenkins-Version: 2.319.3)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1569.vb_72405b_80249"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Credentials (Jenkins-Version: 2.340)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "1143.vb_e8b_b_ceee347"
# Credentials Binding (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "523.vd859a_4b_122e6"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "1.12.1-4"
# Display URL API (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.3.6"
# Durable Task (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "504.vb10d1ae5ba2f"
# ECharts API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "5.4.0-1"
# Font Awesome API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "6.2.1-1"
# Forensics API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "1.17.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.346.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "4.14.3"
# Git client (Jenkins-Version: 2.346.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "3.13.1"
# GitHub (Jenkins-Version: 2.346.1)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.34.5"
# GitHub API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.303-400.v35c2d8258028"
# GitHub Branch Source (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "1696.v3a_7603564d04"
# Gradle (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "2.2"
# HTML Publisher (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.31"
# HTTP Request (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.16"
# InfluxDB (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "3.4"
# Ionicons API (Jenkins-Version: 2.346.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "ionicons-api"
    source:
      version: "31.v4757b_6987003"
# Jackson 2 API (Jenkins-Version: 2.263.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.14.1-313.v504cdd45c18b"
# JaCoCo (Jenkins-Version: 2.277.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.3.2"
# Jakarta Activation API (Jenkins-Version: 2.332.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-activation-api"
    source:
      version: "2.0.1-2"
# Jakarta Mail API (Jenkins-Version: 2.332.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-mail-api"
    source:
      version: "2.0.1-2"
# JavaBeans Activation Framework (JAF) API (Jenkins-Version: 2.332.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-activation-api"
    source:
      version: "1.2.0-5"
# JAXB (Jenkins-Version: 2.332.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jaxb"
    source:
      version: "2.3.7-1"
# Java JSON Web Token (JJWT) (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jjwt-api"
    source:
      version: "0.11.5-77.v646c772fddb_0"
# JQuery3 API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.6.1-2"
# JSch dependency (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jsch"
    source:
      version: "0.1.55.61.va_e9ee26616e7"
# JUnit (Jenkins-Version: 2.346.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1166.va_436e268e972"
# Kubernetes (Jenkins-Version: 2.346.1)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "3743.v1fa_4c724c3b_7"
# Kubernetes Client API (Jenkins-Version: 2.332.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "5.12.2-193.v26a_6078f65a_9" # Do not change this version until Jenkins core version is updated to > 2.346.3.
# Kubernetes Credentials (Jenkins-Version: 2.332.4)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.9.0" # Do not change this version until Jenkins core version is updated to > 2.346.3.
# Kubernetes Credentials Provider (Jenkins-Version: 2.303.3)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "1.206.v7ce2cf7b_0c8b" # Do not change this version until Jenkins core version is updated to > 2.346.3.
# Lockable Resources (Jenkins-Version: 2.289.3)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "2.18"
# Mailer (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "435.438.v5b_81173f5b_a_1"
# Matrix Project (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "772.v494f19991984"
# Metrics (Jenkins-Version: 2.346.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.2.13-420.vea_2f17932dd6"
# OkHttp (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "4.9.3-108.v0feda04578cf"
# Pipeline: Build Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "2.18"
# Pipeline: GitHub (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.8-138.d766e30bb08b"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 2.303.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "38.v445716ea_edda_"
# Pipeline: Groovy Libraries (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-groovy-lib"
    source:
      version: "629.vb_5627b_ee2104"
# Pipeline: Input Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "466.v6d0a_5df34f81"
# Pipeline: Milestone Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "111.v449306f708b_7"
# Pipeline: Model API (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "2.2118.v31fd5b_9944b_5"
# Pipeline: Declarative (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "2.2118.v31fd5b_9944b_5"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "2.2118.v31fd5b_9944b_5"
# Pipeline: Stage Step (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "305.ve96d0205c1c6"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "2.2118.v31fd5b_9944b_5"
# Pipeline Utility Steps (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.15.0"
# Plain Credentials (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "143.v1b_df8b_d3b_e48"
# Plugin Utilities API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "2.20.0"
# Popper.js 2 API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "popper2-api"
    source:
      version: "2.11.6-2"
# Prism API (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "prism-api"
    source:
      version: "1.29.0-2"
# Resource Disposer (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.20"
# SCM API (Jenkins-Version: 2.332.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "631.v9143df5b_e4a_a"
# Script Security (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1229.v4880b_b_e905a_6"
# SnakeYAML API (Jenkins-Version: 2.332.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "1.33-90.v80dcb_3814d35"
# SSH Credentials (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "305.v8f4381501156"
# Structs (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "324.va_f5d6774f3a_d"
# Timestamper (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.21"
# Token Macro (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "321.vd7cc1f2a_52c8"
# Trilead API (Jenkins-Version: 2.319)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "1.67.vc3938a_35172f"
# Variant (Jenkins-Version: 2.319.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "59.vf075fe829ccb"
# Warnings Next Generation (Jenkins-Version: 2.346.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "9.23.0"
# Pipeline (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "590.v6a_d052e5a_a_b_5"
# Pipeline: API (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "1200.v8005c684b_a_c6"
# Pipeline: Basic Steps (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "994.vd57e3ca_46d24"
# Pipeline: Groovy (Jenkins-Version: 2.346.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "3536.vb_8a_6628079d5"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "1217.v38306d8fa_b_5c"
# Pipeline: Job (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "1207.ve6191ff089f8"
# Pipeline: Multibranch (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "716.vc692a_e52371b_"
# Pipeline: SCM Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "400.v6b_89a_1317c9a_"
# Pipeline: Step API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "639.v6eca_cd8c04a_a_"
# Pipeline: Supporting APIs (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "839.v35e2736cfd5c"
# Workspace Cleanup (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.43"
##PLUGINS-END (do not remove!)
