bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        # Use fork until fixes are available in upstream
        # git: https://github.com/jenkinsci/jenkinsfile-runner.git
        # branch: "1.0-beta-30"
        git: https://github.com/SAP/stewardci-jenkinsfilerunner-image
        branch: "jenkinsfile-runner--1.0-beta-30-steward-1"
    docker:
      base: "jenkins/jenkins:2.332.3-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.332.3"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "77c2c1932156cdcfce7d5dcfaf8f14b9e950ba55" #TODO: released commit - is from https://github.com/SAP/elasticsearch-logs-plugin/pull/43


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# JavaScript GUI Lib: ACE Editor bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "ace-editor"
    source:
      version: "1.1"
# Analysis Model API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "10.10.1"
# OWASP Markup Formatter (Jenkins-Version: 2.277.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "2.7"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.13-1.0"
# Authentication Tokens API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.4"
# Bootstrap 5 API (Jenkins-Version: 2.319.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap5-api"
    source:
      version: "5.1.3-7"
# bouncycastle API (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.26"
# Branch API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.1046.v0ca_37783ecc5"
# Build Timeout (Jenkins-Version: 2.332.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.21"
# Caffeine API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "caffeine-api"
    source:
      version: "2.9.3-65.v6a_47d0f4d1fe"
# Checks API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "checks-api"
    source:
      version: "1.7.4"
# Folders (Jenkins-Version: 2.277.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.722.v8165b_a_cf25e9"
# Cobertura (Jenkins-Version: 2.204.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.17"
# Code Coverage API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "2.0.4"
# Configuration as Code (Jenkins-Version: 2.289.3)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1429.v09b_044a_c93de"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Credentials (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "1087.1089.v2f1b_9a_b_040e4"
# Credentials Binding (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "523.vd859a_4b_122e6"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "1.11.4-4"
# Display URL API (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.3.6"
# Durable Task (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "496.va67c6f9eefa7"
# ECharts API (Jenkins-Version: 2.319.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "5.3.2-2"
# Font Awesome API (Jenkins-Version: 2.319.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "6.1.1-1"
# Forensics API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "1.13.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "4.11.3"
# Git client (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "3.11.0"
# GitHub (Jenkins-Version: 2.277.1)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.34.3"
# GitHub API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.303-400.v35c2d8258028"
# GitHub Branch Source (Jenkins-Version: 2.323)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "1637.vd833b_7ca_7654"
# Gradle (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "1.38"
# HTML Publisher (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.30"
# HTTP Request (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.15"
# InfluxDB (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "3.2.1"
# Jackson 2 API (Jenkins-Version: 2.263.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.13.3-285.vc03c0256d517"
# JaCoCo (Jenkins-Version: 2.277.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.3.2"
# JavaBeans Activation Framework (JAF) API (Jenkins-Version: 2.263.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-activation-api"
    source:
      version: "1.2.0-3"
# JavaMail API (Jenkins-Version: 2.263.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-mail-api"
    source:
      version: "1.6.2-6"
# JAXB (Jenkins-Version: 2.263.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jaxb"
    source:
      version: "2.3.6-1"
# Java JSON Web Token (JJWT) (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jjwt-api"
    source:
      version: "0.11.2-71.v2722b_b_06a_2a_f"
# JQuery3 API (Jenkins-Version: 2.319.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.6.0-4"
# JSch dependency (Jenkins-Version: 2.190.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jsch"
    source:
      version: "0.1.55.2"
# JUnit (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1119.va_a_5e9068da_d7"
# Kubernetes (Jenkins-Version: 2.303.3)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "3600.v144b_cd192ca_a_"
# Kubernetes Client API (Jenkins-Version: 2.249)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "5.12.2-193.v26a_6078f65a_9"
# Kubernetes Credentials (Jenkins-Version: 2.222.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.9.0"
# Kubernetes Credentials Provider (Jenkins-Version: 2.222.4)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "0.20"
# Lockable Resources (Jenkins-Version: 2.249.1)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "2.15"
# Mailer (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "414.vcc4c33714601"
# Matrix Project (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "771.v574584b_39e60"
# Metrics (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.1.6.2"
# OkHttp (Jenkins-Version: 2.222.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "4.9.3-105.vb96869f8ac3a"
# Pipeline: Build Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "2.18"
# Pipeline: GitHub (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.8-138.d766e30bb08b"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 2.303.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "38.v445716ea_edda_"
# Pipeline: Groovy Libraries (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-groovy-lib"
    source:
      version: "591.v3a_7f422b_d058"
# Pipeline: Input Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "448.v37cea_9a_10a_70"
# Pipeline: Milestone Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "101.vd572fef9d926"
# Pipeline: Model API (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "2.2086.v12b_420f036e5"
# Pipeline: Declarative (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "2.2086.v12b_420f036e5"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "2.2086.v12b_420f036e5"
# Pipeline: Stage Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "293.v200037eefcd5"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "2.2086.v12b_420f036e5"
# Pipeline Utility Steps (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.12.1"
# Plain Credentials (Jenkins-Version: 2.249.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "1.8"
# Plugin Utilities API (Jenkins-Version: 2.319.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "2.17.0"
# Popper.js 2 API (Jenkins-Version: 2.319.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "popper2-api"
    source:
      version: "2.11.5-2"
# Prism API (Jenkins-Version: 2.319.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "prism-api"
    source:
      version: "1.28.0-2"
# Resource Disposer (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.19"
# SCM API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "608.vfa_f971c5a_a_e9"
# Script Security (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1175.v4b_d517d6db_f0"
# SnakeYAML API (Jenkins-Version: 2.204.6)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "1.30.1"
# SSH Credentials (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "277.v95c2fec1c047"
# Structs (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "318.va_f3ccb_729b_71"
# Timestamper (Jenkins-Version: 2.277.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.17"
# Token Macro (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "293.v283932a_0a_b_49"
# Trilead API (Jenkins-Version: 2.319)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "1.57.v6e90e07157e1"
# Variant (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "1.4"
# Warnings Next Generation (Jenkins-Version: 2.319.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "9.12.0"
# Pipeline (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "581.v0c46fa_697ffd"
# Pipeline: API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "1153.vb_912c0e47fb_a_"
# Pipeline: Basic Steps (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "948.v2c72a_091b_b_68"
# Pipeline: Groovy (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "2706.v71dd22b_c5a_a_2"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "1139.v252a_e12e8463"
# Pipeline: Job (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "1182.v60a_e6279b_579"
# Pipeline: Multibranch (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "716.vc692a_e52371b_"
# Pipeline: SCM Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "400.v6b_89a_1317c9a_"
# Pipeline: Step API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "625.vd896b_f445a_f8"
# Pipeline: Supporting APIs (Jenkins-Version: 2.332.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "820.vd1a_6cc65ef33"
# Workspace Cleanup (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.42"
##PLUGINS-END (do not remove!)
