bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        # Use fork until fixes are available in upstream
        # git: https://github.com/jenkinsci/jenkinsfile-runner.git
        # branch: "1.0-beta-30"
        git: https://github.com/SAP/stewardci-jenkinsfilerunner-image
        branch: "jenkinsfile-runner--1.0-beta-30-steward-1"
    docker:
      base: "jenkins/jenkins:2.319.3-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.319.3"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "0.10.0"


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# JavaScript GUI Lib: ACE Editor bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "ace-editor"
    source:
      version: "1.1"
# Analysis Model API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "10.9.2"
# OWASP Markup Formatter (Jenkins-Version: 2.277.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "2.7"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.13-1.0"
# Authentication Tokens API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.4"
# Bootstrap 4 API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap4-api"
    source:
      version: "4.6.0-3"
# Bootstrap 5 API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap5-api"
    source:
      version: "5.1.3-4"
# bouncycastle API (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.25"
# Branch API (Jenkins-Version: 2.277.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.7.0"
# Build Timeout (Jenkins-Version: 2.222.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.20"
# Caffeine API (Jenkins-Version: 2.222.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "caffeine-api"
    source:
      version: "2.9.2-29.v717aac953ff3"
# Checks API (Jenkins-Version: 2.263.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "checks-api"
    source:
      version: "1.7.2"
# Folders (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.17"
# Cobertura (Jenkins-Version: 2.204.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.17"
# Code Coverage API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "2.0.4"
# Configuration as Code (Jenkins-Version: 2.289.3)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1346.ve8cfa_3473c94"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Credentials (Jenkins-Version: 2.308)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "1074.v60e6c29b_b_44b_"
# Credentials Binding (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "1.27.1"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "1.11.3-6"
# Display URL API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.3.5"
# Durable Task (Jenkins-Version: 2.277.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "493.v195aefbb0ff2"
# ECharts API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "5.2.2-2"
# Font Awesome API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "6.0.0-1"
# Forensics API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "1.7.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "4.10.3"
# Git client (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "3.11.0"
# GIT server (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-server"
    source:
      version: "1.10"
# GitHub (Jenkins-Version: 2.222.4)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.34.2"
# GitHub API (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.301-378.v9807bd746da5"
# GitHub Branch Source (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "2.11.4"
# Gradle (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "1.38"
# JavaScript GUI Lib: Handlebars bundle (Jenkins-Version: 2.204)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "handlebars"
    source:
      version: "3.0.8"
# HTML Publisher (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.29"
# HTTP Request (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.14"
# InfluxDB (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "3.1.1"
# Jackson 2 API (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.13.1-246.va8a9f3eaf46a"
# JaCoCo (Jenkins-Version: 2.277.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.3.1"
# JavaBeans Activation Framework (JAF) API (Jenkins-Version: 2.263.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-activation-api"
    source:
      version: "1.2.0-2"
# JavaMail API (Jenkins-Version: 2.263.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-mail-api"
    source:
      version: "1.6.2-5"
# Java JSON Web Token (JJWT) (Jenkins-Version: 2.222.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jjwt-api"
    source:
      version: "0.11.2-9.c8b45b8bb173"
# JQuery3 API (Jenkins-Version: 2.263.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.6.0-2"
# JSch dependency (Jenkins-Version: 2.190.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jsch"
    source:
      version: "0.1.55.2"
# JUnit (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1.54"
# Kubernetes (Jenkins-Version: 2.303.3)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "1.31.3"
# Kubernetes Client API (Jenkins-Version: 2.249)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "5.11.2-182.v0f1cf4c5904e"
# Kubernetes Credentials (Jenkins-Version: 2.222.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.9.0"
# Kubernetes Credentials Provider (Jenkins-Version: 2.222.4)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "0.20"
# Lockable Resources (Jenkins-Version: 2.249.1)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "2.14"
# Mailer (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "408.vd726a_1130320"
# Matrix Project (Jenkins-Version: 2.282)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "1.20"
# Metrics (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.1.6.1"
# JavaScript GUI Lib: Moment.js bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "momentjs"
    source:
      version: "1.1.1"
# OkHttp (Jenkins-Version: 2.222.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "4.9.3-105.vb96869f8ac3a"
# Pipeline: Build Step (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "2.15"
# Pipeline: GitHub (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.8-138.d766e30bb08b"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "36.v4c01db_ca_ed16"
# Pipeline Graph Analysis (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-graph-analysis"
    source:
      version: "188.v3a01e7973f2c"
# Pipeline: Input Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "446.vf27b_0b_83500e"
# Pipeline: Milestone Step (Jenkins-Version: 2.277.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "100.v60a_03cd446e1"
# Pipeline: Model API (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "1.9.3"
# Pipeline: Declarative (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "1.9.3"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "1.9.3"
# Pipeline: REST API (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-rest-api"
    source:
      version: "2.21"
# Pipeline: Stage Step (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "291.vf0a8a7aeeb50"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "1.9.3"
# Pipeline: Stage View (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-stage-view"
    source:
      version: "2.21"
# Pipeline Utility Steps (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.12.0"
# Plain Credentials (Jenkins-Version: 2.249.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "1.8"
# Plugin Utilities API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "2.13.0"
# Popper.js API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "popper-api"
    source:
      version: "1.16.1-2"
# Popper.js 2 API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "popper2-api"
    source:
      version: "2.11.2-1"
# Prism API (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "prism-api"
    source:
      version: "1.26.0-2"
# Resource Disposer (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.17"
# SCM API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "595.vd5a_df5eb_0e39"
# Script Security (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1131.v8b_b_5eda_c328e"
# Snakeyaml API (Jenkins-Version: 2.204.6)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "1.29.1"
# SSH Credentials (Jenkins-Version: 2.282)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "1.19"
# SSH server (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.modules"
    artifactId: "sshd"
    source:
      version: "3.1.0"
# Structs (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "308.v852b473a2b8c"
# Timestamper (Jenkins-Version: 2.277.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.17"
# Token Macro (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "277.v7c8f82a_d66b_3"
# Trilead API (Jenkins-Version: 2.204)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "1.0.13"
# Variant (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "1.4"
# Warnings Next Generation (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "9.11.0"
# Pipeline (Jenkins-Version: 2.130)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "2.6"
# Pipeline: API (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "1136.v7f5f1759dc16"
# Pipeline: Basic Steps (Jenkins-Version: 2.263.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "2.24"
# Pipeline: Groovy (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "2648.va9433432b33c"
# Pipeline: Shared Groovy Libraries (Jenkins-Version: 2.303.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps-global-lib"
    source:
      version: "552.vd9cc05b8a2e1"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "1121.va_65b_d2701486"
# Pipeline: Job (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "1145.v7f2433caa07f"
# Pipeline: Multibranch (Jenkins-Version: 2.277.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "706.vd43c65dec013"
# Pipeline: SCM Step (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "2.13"
# Pipeline: Step API (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "622.vb_8e7c15b_c95a_"
# Pipeline: Supporting APIs (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "813.vb_d7c3d2984a_0"
# Workspace Cleanup (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.40"
##PLUGINS-END (do not remove!)
