bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner
        branch: "1.0-beta-32"
    docker:
      base: "jenkins/jenkins:2.452.2-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    # In order to avoid severe backwards compatibility issues,
    # keep the Jenkins core version in sync with the used one
    # in the chosen jenkinsfile-runner release
    version: "2.452.2"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "0.14.2"


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# Analysis Model API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "12.3.3"
# OWASP Markup Formatter (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "162.v0e6ec0fcfcf6"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.14-208.v438351942757"
# Apache HttpComponents Client 5.x API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "apache-httpcomponents-client-5-api"
    source:
      version: "5.3.1-1.0"
# ASM API (Jenkins-Version: 2.414.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "asm-api"
    source:
      version: "9.7-33.v4d23ef79fcc8"
# Authentication Tokens API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.113.v81215a_241826"
# Bootstrap 5 API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap5-api"
    source:
      version: "5.3.3-1"
# bouncycastle API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.30.1.78.1-233.vfdcdeb_0a_08a_a_"
# Branch API (Jenkins-Version: 2.426.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.1169.va_f810c56e895"
# Build Timeout (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.32"
# Caffeine API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "caffeine-api"
    source:
      version: "3.1.8-133.v17b_1ff2e0599"
# Checks API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "checks-api"
    source:
      version: "2.2.0"
# Folders (Jenkins-Version: 2.444)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.928.v7c780211d66e"
# Cobertura (Jenkins-Version: 2.204.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.17"
# Code Coverage (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "4.99.0"
# commons-lang3 v3.x Jenkins API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-lang3-api"
    source:
      version: "3.14.0-76.vda_5591261cfe"
# commons-text API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-text-api"
    source:
      version: "1.12.0-119.v73ef73f2345d"
# Configuration as Code (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1810.v9b_c30a_249a_4c"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Coverage (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "coverage"
    source:
      version: "1.15.0"
# Credentials (Jenkins-Version: 2.426.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "1337.v60b_d7b_c7b_c9f"
# Credentials Binding (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "677.vdc9d38cb_254d"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "2.0.8-1"
# Display URL API (Jenkins-Version: 2.361.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.204.vf6fddd8a_8b_e9"
# Durable Task (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "555.v6802fe0f0b_82"
# ECharts API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "5.5.0-1"
# Font Awesome API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "6.5.2-1"
# Forensics API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "2.4.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.426.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "5.2.2"
# Git client (Jenkins-Version: 2.440.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "5.0.0"
# GitHub (Jenkins-Version: 2.414.3)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.39.0"
# GitHub API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.318-461.v7a_c09c9fa_d63"
# GitHub Branch Source (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "1789.v5b_0c0cea_18c3"
# Gradle (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "2.12"
# Gson API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "gson-api"
    source:
      version: "2.11.0-41.v019fcf6125dc"
# HTML Publisher (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.34"
# HTTP Request (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.18"
# InfluxDB (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "3.6.1"
# Instance Identity (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.modules"
    artifactId: "instance-identity"
    source:
      version: "185.v303dc7c645f9"
# Ionicons API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "ionicons-api"
    source:
      version: "74.v93d5eb_813d5f"
# Jackson 2 API (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.17.0-379.v02de8ec9f64c"
# JaCoCo (Jenkins-Version: 2.426.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.3.6"
# Jakarta Activation API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-activation-api"
    source:
      version: "2.1.3-1"
# Jakarta Mail API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-mail-api"
    source:
      version: "2.1.3-1"
# JavaBeans Activation Framework (JAF) API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-activation-api"
    source:
      version: "1.2.0-7"
# JAXB (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "jaxb"
    source:
      version: "2.3.9-1"
# Java JSON Web Token (JJWT) (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jjwt-api"
    source:
      version: "0.11.5-112.ve82dfb_224b_a_d"
# Joda Time API (Jenkins-Version: 2.401.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "joda-time-api"
    source:
      version: "2.12.7-29.v5a_b_e3a_82269a_"
# JQuery3 API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.7.1-2"
# JSON Api (Jenkins-Version: 2.414.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "json-api"
    source:
      version: "20240303-41.v94e11e6de726"
# JSON Path API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "json-path-api"
    source:
      version: "2.9.0-58.v62e3e85b_a_655"
# JUnit (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1265.v65b_14fa_f12f0"
# Kubernetes (Jenkins-Version: 2.426.3)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "4246.v5a_12b_1fe120e"
# Kubernetes Client API (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "6.10.0-240.v57880ce8b_0b_2"
# Kubernetes Credentials (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "174.va_36e093562d9"
# Kubernetes Credentials Provider (Jenkins-Version: 2.414.1)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "1.262.v2670ef7ea_0c5"
# Lockable Resources (Jenkins-Version: 2.440.1)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "1255.vf48745da_35d0"
# Mailer (Jenkins-Version: 2.440.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "472.vf7c289a_4b_420"
# Matrix Project (Jenkins-Version: 2.440.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "832.va_66e270d2946"
# Metrics (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.2.21-451.vd51df8df52ec"
# Mina SSHD API :: Common (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins.mina-sshd-api"
    artifactId: "mina-sshd-api-common"
    source:
      version: "2.12.1-113.v4d3ea_5eb_7f72"
# Mina SSHD API :: Core (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins.mina-sshd-api"
    artifactId: "mina-sshd-api-core"
    source:
      version: "2.12.1-113.v4d3ea_5eb_7f72"
# OkHttp (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "4.11.0-172.vda_da_1feeb_c6e"
# Pipeline: Build Step (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "540.vb_e8849e1a_b_d8"
# Pipeline: GitHub (Jenkins-Version: 2.375.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.8-159.09e4403bc62f"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "61.v629f2cc41d83"
# Pipeline: Groovy Libraries (Jenkins-Version: 2.414.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-groovy-lib"
    source:
      version: "727.ve832a_9244dfa_"
# Pipeline: Input Step (Jenkins-Version: 2.440)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "495.ve9c153f6067b_"
# Pipeline: Milestone Step (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "119.vdfdc43fc3b_9a_"
# Pipeline: Model API (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "2.2198.v41dd8ef6dd56"
# Pipeline: Declarative (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "2.2198.v41dd8ef6dd56"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "2.2198.v41dd8ef6dd56"
# Pipeline: Stage Step (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "312.v8cd10304c27a_"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "2.2198.v41dd8ef6dd56"
# Pipeline Utility Steps (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.16.2"
# Plain Credentials (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "182.v468b_97b_9dcb_8"
# Plugin Utilities API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "4.1.0"
# Prism API (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "prism-api"
    source:
      version: "1.29.0-15"
# Resource Disposer (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.23"
# SCM API (Jenkins-Version: 2.426.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "690.vfc8b_54395023"
# Script Security (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1341.va_2819b_414686"
# SnakeYAML API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "2.2-111.vc6598e30cc65"
# SSH Credentials (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "337.v395d2403ccd4"
# Structs (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "337.v1b_04ea_4df7c8"
# Timestamper (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.27"
# Token Macro (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "400.v35420b_922dcb_"
# Variant (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "60.v7290fc0eb_b_cd"
# Warnings (Jenkins-Version: 2.426.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "10.7.0"
# Pipeline (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "596.v8c21c963d92d"
# Pipeline: API (Jenkins-Version: 2.426.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "1316.v33eb_726c50b_a_"
# Pipeline: Basic Steps (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "1058.vcb_fc1e3a_21a_9"
# Pipeline: Groovy (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "3903.v48a_8836749e9"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.440.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "1353.v1891a_b_01da_18"
# Pipeline: Job (Jenkins-Version: 2.440)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "1400.v7fd111b_ec82f"
# Pipeline: Multibranch (Jenkins-Version: 2.452.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "783.787.v50539468395f"
# Pipeline: SCM Step (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "427.v4ca_6512e7df1"
# Pipeline: Step API (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "657.v03b_e8115821b_"
# Pipeline: Supporting APIs (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "907.v6713a_ed8a_573"
# Workspace Cleanup (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.46"
##PLUGINS-END (do not remove!)
