bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner
        # Change to release tag when release > 1.0-beta-31 exists
        commit: "1.0-beta-32"
    docker:
      base: "jenkins/jenkins:2.426.3-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    # In order to avoid severe backwards compatibility issues,
    # keep the Jenkins core version in sync with the used one
    # in the chosen jenkinsfile-runner release
    version: "2.426.3"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "0.14.2"


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# Analysis Model API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "11.10.0"
# OWASP Markup Formatter (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "162.v0e6ec0fcfcf6"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.14-208.v438351942757"
# Authentication Tokens API (Jenkins-Version: 2.387.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.53.v1c90fd9191a_b_"
# Bootstrap 5 API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap5-api"
    source:
      version: "5.3.2-1"
# bouncycastle API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.29"
# Branch API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.1128.v717130d4f816"
# Build Timeout (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.31"
# Caffeine API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "caffeine-api"
    source:
      version: "3.1.8-133.v17b_1ff2e0599"
# Checks API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "checks-api"
    source:
      version: "2.0.2"
# Folders (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.848.ve3b_fd7839a_81"
# Cobertura (Jenkins-Version: 2.204.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.17"
# Code Coverage (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "4.9.0"
# commons-lang3 v3.x Jenkins API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-lang3-api"
    source:
      version: "3.13.0-62.v7d18e55f51e2"
# commons-text API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-text-api"
    source:
      version: "1.10.0-78.v3e7b_ea_d5a_fe1"
# Configuration as Code (Jenkins-Version: 2.414.1)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1714.v09593e830cfa"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Credentials (Jenkins-Version: 2.387.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "1293.vff276f713473"
# Credentials Binding (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "636.v55f1275c7b_27"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "1.13.6-5"
# Display URL API (Jenkins-Version: 2.361.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.200.vb_9327d658781"
# Durable Task (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "523.va_a_22cf15d5e0"
# ECharts API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "5.4.0-6"
# Font Awesome API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "6.4.2-1"
# Forensics API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "2.3.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "5.2.0"
# Git client (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "4.5.0"
# GitHub (Jenkins-Version: 2.387.3)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.37.3"
# GitHub API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.316-451.v15738eef3414"
# GitHub Branch Source (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "1741.va_3028eb_9fd21"
# Gradle (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "2.8.2"
# HTML Publisher (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.32"
# HTTP Request (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.18"
# InfluxDB (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "3.5"
# Instance Identity (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.modules"
    artifactId: "instance-identity"
    source:
      version: "173.va_37c494ec4e5"
# Ionicons API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "ionicons-api"
    source:
      version: "56.v1b_1c8c49374e"
# Jackson 2 API (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.15.3-366.vfe8d1fa_f8c87"
# JaCoCo (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.3.5"
# Jakarta Activation API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-activation-api"
    source:
      version: "2.0.1-3"
# Jakarta Mail API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-mail-api"
    source:
      version: "2.0.1-3"
# JavaBeans Activation Framework (JAF) API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-activation-api"
    source:
      version: "1.2.0-6"
# JAXB (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jaxb"
    source:
      version: "2.3.8-1"
# Java JSON Web Token (JJWT) (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jjwt-api"
    source:
      version: "0.11.5-77.v646c772fddb_0"
# JQuery3 API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.7.1-1"
# JUnit (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1240.vf9529b_881428"
# Kubernetes (Jenkins-Version: 2.401.1)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "4054.v2da_8e2794884"
# Kubernetes Client API (Jenkins-Version: 2.401.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "6.8.1-224.vd388fca_4db_3b_"
# Kubernetes Credentials (Jenkins-Version: 2.401.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.11"
# Kubernetes Credentials Provider (Jenkins-Version: 2.414.1)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "1.238.v637de1db_9e80"
# Lockable Resources (Jenkins-Version: 2.387.3)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "1185.v0c528656ce04"
# Mailer (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "463.vedf8358e006b_"
# Matrix Project (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "818.v7eb_e657db_924"
# Metrics (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.2.18-442.v02e107157925"
# Mina SSHD API :: Common (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins.mina-sshd-api"
    artifactId: "mina-sshd-api-common"
    source:
      version: "2.10.0-69.v28e3e36d18eb_"
# Mina SSHD API :: Core (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins.mina-sshd-api"
    artifactId: "mina-sshd-api-core"
    source:
      version: "2.10.0-69.v28e3e36d18eb_"
# OkHttp (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "4.11.0-157.v6852a_a_fa_ec11"
# Pipeline: Build Step (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "505.v5f0844d8d126"
# Pipeline: GitHub (Jenkins-Version: 2.375.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.8-155.8eab375ac9f8"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "42.v0739460cda_c4"
# Pipeline: Groovy Libraries (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-groovy-lib"
    source:
      version: "689.veec561a_dee13"
# Pipeline: Input Step (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "477.v339683a_8d55e"
# Pipeline: Milestone Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "111.v449306f708b_7"
# Pipeline: Model API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "2.2144.v077a_d1928a_40"
# Pipeline: Declarative (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "2.2144.v077a_d1928a_40"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "2.2144.v077a_d1928a_40"
# Pipeline: Stage Step (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "305.ve96d0205c1c6"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "2.2144.v077a_d1928a_40"
# Pipeline Utility Steps (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.16.0"
# Plain Credentials (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "143.v1b_df8b_d3b_e48"
# Plugin Utilities API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "3.6.0"
# Prism API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "prism-api"
    source:
      version: "1.29.0-8"
# Resource Disposer (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.23"
# SCM API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "676.v886669a_199a_a_"
# Script Security (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1275.v23895f409fb_d"
# SnakeYAML API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "2.2-111.vc6598e30cc65"
# SSH Credentials (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "308.ve4497b_ccd8f4"
# Structs (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "325.vcb_307d2a_2782"
# Timestamper (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.26"
# Token Macro (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "384.vf35b_f26814ec"
# Trilead API (Jenkins-Version: 2.361)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "2.84.v72119de229b_7"
# Variant (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "60.v7290fc0eb_b_cd"
# Warnings (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "10.5.0"
# Pipeline (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "596.v8c21c963d92d"
# Pipeline: API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "1283.v99c10937efcb_"
# Pipeline: Basic Steps (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "1042.ve7b_140c4a_e0c"
# Pipeline: Groovy (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "3802.vd42b_fcf00b_a_c"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "1289.v4d3e7b_01546b_"
# Pipeline: Job (Jenkins-Version: 2.414)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "1348.v32a_a_f150910e"
# Pipeline: Multibranch (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "756.v891d88f2cd46"
# Pipeline: SCM Step (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "415.v434365564324"
# Pipeline: Step API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "639.v6eca_cd8c04a_a_"
# Pipeline: Supporting APIs (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "865.v43e78cc44e0d"
# Workspace Cleanup (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.45"
##PLUGINS-END (do not remove!)
