bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        # Use fork until fixes are available in upstream
        # git: https://github.com/jenkinsci/jenkinsfile-runner.git
        # branch: "1.0-beta-19"
        git: https://github.com/SAP/stewardci-jenkinsfilerunner-image
        branch: "jenkinsfile-runner--1.0-beta-27-steward-1"
    docker:
      base: "jenkins/jenkins:2.277.4-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.277.4"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "v0.2.8"


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# JavaScript GUI Lib: ACE Editor bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "ace-editor"
    source:
      version: "1.1"
# Analysis Model API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "10.2.5"
# OWASP Markup Formatter (Jenkins-Version: 2.121.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "2.1"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.13-1.0"
# Authentication Tokens API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.4"
# Bootstrap 4 API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap4-api"
    source:
      version: "4.6.0-3"
# bouncycastle API (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.20"
# Branch API (Jenkins-Version: 2.277.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.6.4"
# Build Timeout (Jenkins-Version: 2.222.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.20"
# Caffeine API (Jenkins-Version: 2.222.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "caffeine-api"
    source:
      version: "2.9.1-23.v51c4e2c879c8"
# Checks API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "checks-api"
    source:
      version: "1.7.0"
# Folders (Jenkins-Version: 2.204.6)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.15"
# Cobertura (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.16"
# Code Coverage API (Jenkins-Version: 2.222.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "1.3.2"
# Configuration as Code (Jenkins-Version: 2.222.1)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1.51"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Credentials (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "2.3.19"
# Credentials Binding (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "1.24"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "1.10.23-3"
# Display URL API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.3.4"
# Durable Task (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "1.36"
# ECharts API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "5.1.0-2"
# Font Awesome API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "5.15.3-2"
# Forensics API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "1.0.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.263.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "4.7.1"
# Git client (Jenkins-Version: 2.263.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "3.7.1"
# GIT server (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-server"
    source:
      version: "1.9"
# GitHub (Jenkins-Version: 2.222.4)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.33.1"
# GitHub API (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.123"
# GitHub Branch Source (Jenkins-Version: 2.277.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "2.10.4"
# Gradle (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "1.36"
# JavaScript GUI Lib: Handlebars bundle (Jenkins-Version: 2.204)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "handlebars"
    source:
      version: "3.0.8"
# HTML Publisher (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.25"
# HTTP Request (Jenkins-Version: 2.204.6)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.9.0"
# InfluxDB (Jenkins-Version: 2.195)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "3.0"
# Jackson 2 API (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.12.3"
# JaCoCo (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.1.1"
# Java JSON Web Token (JJWT) (Jenkins-Version: 2.222.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jjwt-api"
    source:
      version: "0.11.2-9.c8b45b8bb173"
# JQuery3 API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.6.0-1"
# JSch dependency (Jenkins-Version: 2.190.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jsch"
    source:
      version: "0.1.55.2"
# JUnit (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1.49"
# Kubernetes (Jenkins-Version: 2.263)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "1.29.4"
# Kubernetes Client API (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "4.13.3-1"
# Kubernetes Credentials (Jenkins-Version: 2.204.6)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.8.0"
# Kubernetes Credentials Provider (Jenkins-Version: 2.190.1)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "0.18-1"
# Lockable Resources (Jenkins-Version: 2.138.4)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "2.10"
# Mailer (Jenkins-Version: 2.235.5)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "1.34"
# Matrix Project (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "1.18"
# Metrics (Jenkins-Version: 2.222.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.0.2.7"
# JavaScript GUI Lib: Moment.js bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "momentjs"
    source:
      version: "1.1.1"
# OkHttp (Jenkins-Version: 2.164.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "3.14.9"
# Pipeline: Build Step (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "2.13"
# Pipeline: GitHub (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.7"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "1.0"
# Pipeline Graph Analysis (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-graph-analysis"
    source:
      version: "1.10"
# Pipeline: Input Step (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "2.12"
# Pipeline: Milestone Step (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "1.3.2"
# Pipeline: Model API (Jenkins-Version: 2.190.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "1.8.4"
# Pipeline: Declarative (Jenkins-Version: 2.190.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "1.8.4"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.190.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "1.8.4"
# Pipeline: REST API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-rest-api"
    source:
      version: "2.19"
# Pipeline: Stage Step (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "2.5"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.190.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "1.8.4"
# Pipeline: Stage View (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-stage-view"
    source:
      version: "2.19"
# Pipeline Utility Steps (Jenkins-Version: 2.121.2)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.7.1"
# Plain Credentials (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "1.7"
# Plugin Utilities API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "2.2.0"
# Popper.js API (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "popper-api"
    source:
      version: "1.16.1-2"
# Resource Disposer (Jenkins-Version: 2.164.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.15"
# SCM API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "2.6.4"
# Script Security (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1.76"
# Snakeyaml API (Jenkins-Version: 2.204.6)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "1.27.0"
# SSH Credentials (Jenkins-Version: 2.190.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "1.18.1"
# Structs (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "1.23"
# Timestamper (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.13"
# Token Macro (Jenkins-Version: 2.274)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "2.15"
# Trilead API (Jenkins-Version: 2.204)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "1.0.13"
# Variant (Jenkins-Version: 2.249.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "1.4"
# Warnings Next Generation (Jenkins-Version: 2.249.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "9.1.0"
# Pipeline (Jenkins-Version: 2.130)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "2.6"
# Pipeline: API (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "2.42"
# Pipeline: Basic Steps (Jenkins-Version: 2.263)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "2.23"
# Pipeline: Groovy (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "2.91"
# Pipeline: Shared Groovy Libraries (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps-global-lib"
    source:
      version: "2.19"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.248)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "2.38"
# Pipeline: Job (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "2.40"
# Pipeline: Multibranch (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "2.23"
# Pipeline: SCM Step (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "2.12"
# Pipeline: Step API (Jenkins-Version: 2.176.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "2.23"
# Pipeline: Supporting APIs (Jenkins-Version: 2.222.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "3.8"
# Workspace Cleanup (Jenkins-Version: 2.164.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.39"
##PLUGINS-END (do not remove!)
