bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner.git
        branch: "1.0-beta-11"
    docker:
      base: "jenkins/jenkins:2.204.1-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.204.1"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "cd5a3c75740408c742bed05bca1772b6e5935e10" #TODO: TEST ONLY


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

# Ant (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ant"
    source:
      version: "1.10"
# Structs (Jenkins-Version: 2.107.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "1.20"
# Badge (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "badge"
    source:
      version: "1.8"
# Pipeline: Step API (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "2.22"
# OWASP Markup Formatter (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "1.6"
# Script Security (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1.68"
# Build Timeout (Jenkins-Version: 1.625.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.19"
# Naginator (Jenkins-Version: 1.565)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "naginator"
    source:
      version: "1.18"
# Matrix Project (Jenkins-Version: 2.7.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "1.14"
# JUnit (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1.28"
# Pipeline: API (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "2.38"
# SCM API (Jenkins-Version: 2.107.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "2.6.3"
# Token Macro (Jenkins-Version: 2.121.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "2.10"
# Checkmarx (Jenkins-Version: 1.579)
  - groupId: "com.checkmarx.jenkins"
    artifactId: "checkmarx"
    source:
      version: "8.90.4"
# Maven Integration (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.main"
    artifactId: "maven-plugin"
    source:
      version: "3.4"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.10-2.0"
# Javadoc (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "javadoc"
    source:
      version: "1.5"
# JSch dependency (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jsch"
    source:
      version: "0.1.55.1"
# SSH Credentials (Jenkins-Version: 2.190.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "1.18"
# Credentials (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "2.3.0"
# Configuration as Code (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1.34"
# Trilead API (Jenkins-Version: 2.184)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "1.0.5"
# Mailer (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "1.29"
# Display URL API (Jenkins-Version: 2.89.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.3.2"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Credentials Binding (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "1.20"
# Plain Credentials (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "1.5"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# Email Extension (Jenkins-Version: 2.121.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "email-ext"
    source:
      version: "2.68"
# Pipeline: Job (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "2.36"
# Pipeline: Supporting APIs (Jenkins-Version: 2.121.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "3.3"
# Config File Provider (Jenkins-Version: 2.121.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "config-file-provider"
    source:
      version: "3.6.3"
# Folders (Jenkins-Version: 2.130)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.10.1"
# Static Analysis Utilities (Jenkins-Version: 1.625.1)
  - groupId: "org.jvnet.hudson.plugins"
    artifactId: "analysis-core"
    source:
      version: "1.96"
# Dashboard View (Jenkins-Version: 2.89.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "dashboard-view"
    source:
      version: "2.12"
# Git (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "4.0.0"
# Pipeline: SCM Step (Jenkins-Version: 2.60)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "2.9"
# Git client (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "3.0.0"
# Parameterized Trigger (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "parameterized-trigger"
    source:
      version: "2.36"
# Conditional BuildStep (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "conditional-buildstep"
    source:
      version: "1.3.6"
# Run Condition (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "run-condition"
    source:
      version: "1.2"
# promoted builds (Jenkins-Version: 2.121.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "promoted-builds"
    source:
      version: "3.5"
# Rebuilder (Jenkins-Version: 2.32.2)
  - groupId: "com.sonyericsson.hudson.plugins.rebuild"
    artifactId: "rebuild"
    source:
      version: "1.31"
# Project Inheritance (Jenkins-Version: 2.107.3)
  - groupId: "hudson.plugins"
    artifactId: "project-inheritance"
    source:
      version: "19.08.02"
# Job DSL (Jenkins-Version: 2.121)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "job-dsl"
    source:
      version: "1.76"
# vSphere (Jenkins-Version: 1.625.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "vsphere-cloud"
    source:
      version: "2.21"
# Pipeline: Basic Steps (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "2.19"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "2.35"
# Durable Task (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "1.33"
# Node Iterator API (Jenkins-Version: 1.625.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "node-iterator-api"
    source:
      version: "1.5.0"
# SSH Slaves (Jenkins-Version: 2.190.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-slaves"
    source:
      version: "1.31.0"
# Managed Scripts (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "managed-scripts"
    source:
      version: "1.4"
# Subversion (Jenkins-Version: 2.107.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "subversion"
    source:
      version: "2.13.0"
# MapDB API (Jenkins-Version: 1.565)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mapdb-api"
    source:
      version: "1.0.9.0"
# FindBugs (Jenkins-Version: 1.625.1)
  - groupId: "org.jvnet.hudson.plugins"
    artifactId: "findbugs"
    source:
      version: "5.0.0"
# Gatling (Jenkins-Version: 2.7.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.2.7"
# Pipeline: Groovy (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "2.78"
# Support Core (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "support-core"
    source:
      version: "2.65"
# Async Http Client (Jenkins-Version: 1.625.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "async-http-client"
    source:
      version: "1.9.40.0"
# Metrics (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.0.2.6"
# Jackson 2 API (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.10.2"
# Variant (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "1.3"
# JavaScript GUI Lib: ACE Editor bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "ace-editor"
    source:
      version: "1.1"
# JavaScript GUI Lib: jQuery bundles (jQuery and jQuery UI) (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "jquery-detached"
    source:
      version: "1.2.1"
# GitHub (Jenkins-Version: 2.60.3)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.29.5"
# GitHub API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.95"
# Gradle (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "1.36"
# HTML Publisher (Jenkins-Version: 1.609.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.21"
# HTTP Request (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.8.24"
# InfluxDB (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "2.0.4"
# Cobertura (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.15"
# Code Coverage API (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "1.1.2"
# Branch API (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.5.5"
# JaCoCo (Jenkins-Version: 2.54)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.0.4"
# Performance (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "performance"
    source:
      version: "3.17"
# Performance Publisher (Jenkins-Version: 1.625.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "perfpublisher"
    source:
      version: "8.09"
# Robot Framework (Jenkins-Version: 2.7.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "robot"
    source:
      version: "2.0.0"
# Kubernetes (Jenkins-Version: 2.190.1)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "1.22.4"
# Docker Commons (Jenkins-Version: 2.150.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "docker-commons"
    source:
      version: "1.16"
# Authentication Tokens API (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.3"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "1.5.0"
# Pipeline: Stage Step (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "2.3"
# Pipeline: Model API (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "1.5.0"
# Kubernetes Client API (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "4.6.4-2"
# bouncycastle API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.18"
# Kubernetes Credentials (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.4.1"
# Kubernetes Credentials Provider (Jenkins-Version: 2.176.1)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "0.13"
# CloudBees AWS Credentials (Jenkins-Version: 2.73.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "aws-credentials"
    source:
      version: "1.28"
# Amazon Web Services SDK (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "aws-java-sdk"
    source:
      version: "1.11.700"
# Nexus Artifact Uploader (Jenkins-Version: 1.651.3)
  - groupId: "sp.sd"
    artifactId: "nexus-artifact-uploader"
    source:
      version: "2.10"
# Pipeline: GitHub (Jenkins-Version: 2.128)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.5"
# GitHub Branch Source (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "2.5.8"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "1.0"
# Pipeline: Shared Groovy Libraries (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps-global-lib"
    source:
      version: "2.15"
# GIT server (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-server"
    source:
      version: "1.9"
# Pipeline Utility Steps (Jenkins-Version: 2.121.2)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.3.1"
# PMD (Jenkins-Version: 1.625.1)
  - groupId: "org.jvnet.hudson.plugins"
    artifactId: "pmd"
    source:
      version: "4.0.0"
# SSH Agent (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-agent"
    source:
      version: "1.17"
# Timestamper (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.10"
# Warnings (Jenkins-Version: 2.89.1)
  - groupId: "org.jvnet.hudson.plugins"
    artifactId: "warnings"
    source:
      version: "5.0.1"
# Warnings Next Generation (Jenkins-Version: 2.138.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "7.3.0"
# Analysis Model API (Jenkins-Version: 2.138.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "7.0.4"
# Forensics API (Jenkins-Version: 2.138.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "0.6.1"
# Pipeline (Jenkins-Version: 2.130)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "2.6"
# Lockable Resources (Jenkins-Version: 2.60.3)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "2.7"
# Pipeline: Stage View (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-stage-view"
    source:
      version: "2.12"
# Pipeline: REST API (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins.pipeline-stage-view"
    artifactId: "pipeline-rest-api"
    source:
      version: "2.12"
# Pipeline Graph Analysis (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-graph-analysis"
    source:
      version: "1.10"
# Pipeline: Input Step (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "2.11"
# JavaScript GUI Lib: Handlebars bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "handlebars"
    source:
      version: "1.1.1"
# JavaScript GUI Lib: Moment.js bundle (Jenkins-Version: 1.580.1)
  - groupId: "org.jenkins-ci.ui"
    artifactId: "momentjs"
    source:
      version: "1.1.1"
# Pipeline: Multibranch (Jenkins-Version: 2.121.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "2.21"
# Pipeline: Build Step (Jenkins-Version: 2.138.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "2.11"
# Pipeline: Milestone Step (Jenkins-Version: 1.642.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "1.3.1"
# Pipeline: Declarative (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "1.5.0"
# Docker Pipeline (Jenkins-Version: 2.60.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "docker-workflow"
    source:
      version: "1.21"
# Pipeline: Declarative Agent API (Jenkins-Version: 2.7.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-declarative-agent"
    source:
      version: "1.1.1"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.176.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "1.5.0"
# Workspace Cleanup (Jenkins-Version: 2.121)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.38"
# Resource Disposer (Jenkins-Version: 2.54)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.14"
