bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner
        # Change to release tag when release > 1.0-beta-31 exists
        commit: "d1efba38f567333a4563e5aba0ec9d907073c742"
    docker:
      base: "jenkins/jenkins:2.387.3-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    # In order to avoid severe backwards compatibility issues,
    # keep the Jenkins core version in sync with the used one
    # in the chosen jenkinsfile-runner release
    version: "2.387.3"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "0.13.1"


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# Analysis Model API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "11.6.0"
# OWASP Markup Formatter (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "162.v0e6ec0fcfcf6"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.14-150.v7a_b_9d17134a_5"
# Authentication Tokens API (Jenkins-Version: 2.387.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.53.v1c90fd9191a_b_"
# Bootstrap 5 API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap5-api"
    source:
      version: "5.3.0-1"
# bouncycastle API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.29"
# Branch API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.1122.v09cb_8ea_8a_724"
# Build Timeout (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.31"
# Caffeine API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "caffeine-api"
    source:
      version: "3.1.6-115.vb_8b_b_328e59d8"
# Checks API (Jenkins-Version: 2.387.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "checks-api"
    source:
      version: "2.0.0"
# Folders (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.846.v23698686f0f6"
# Cobertura (Jenkins-Version: 2.204.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.17"
# Code Coverage API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "4.7.0"
# commons-lang3 v3.x Jenkins API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-lang3-api"
    source:
      version: "3.13.0-62.v7d18e55f51e2"
# commons-text API (Jenkins-Version: 2.361.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-text-api"
    source:
      version: "1.10.0-68.v0d0b_c439292b_"
# Configuration as Code (Jenkins-Version: 2.387.1)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1670.v564dc8b_982d0"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Credentials (Jenkins-Version: 2.387.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "1271.v54b_1c2c6388a_"
# Credentials Binding (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "631.v861c06d062b_4"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "1.13.5-1"
# Display URL API (Jenkins-Version: 2.361.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.3.8"
# Durable Task (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "513.vc48a_a_075a_d93"
# ECharts API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "5.4.0-5"
# Font Awesome API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "6.4.0-2"
# Forensics API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "2.3.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "5.2.0"
# Git client (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "4.4.0"
# GitHub (Jenkins-Version: 2.361.4)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.37.2"
# GitHub API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.314-431.v78d72a_3fe4c3"
# GitHub Branch Source (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "1732.v3f1889a_c475b_"
# Gradle (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "2.8.2"
# HTML Publisher (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.32"
# HTTP Request (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.18"
# InfluxDB (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "3.5"
# Instance Identity (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.modules"
    artifactId: "instance-identity"
    source:
      version: "173.va_37c494ec4e5"
# Ionicons API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "ionicons-api"
    source:
      version: "56.v1b_1c8c49374e"
# Jackson 2 API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.15.2-350.v0c2f3f8fc595"
# JaCoCo (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.3.4"
# Jakarta Activation API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-activation-api"
    source:
      version: "2.0.1-3"
# Jakarta Mail API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-mail-api"
    source:
      version: "2.0.1-3"
# JavaBeans Activation Framework (JAF) API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-activation-api"
    source:
      version: "1.2.0-6"
# JAXB (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jaxb"
    source:
      version: "2.3.8-1"
# Java JSON Web Token (JJWT) (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jjwt-api"
    source:
      version: "0.11.5-77.v646c772fddb_0"
# JQuery3 API (Jenkins-Version: 2.387.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.7.0-1"
# JUnit (Jenkins-Version: 2.387.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1217.v4297208a_a_b_ce"
# Kubernetes (Jenkins-Version: 2.387.3)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "3985.vd26d77b_2a_48a_"
# Kubernetes Client API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "6.4.1-215.v2ed17097a_8e9"
# Kubernetes Credentials (Jenkins-Version: 2.332.4)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.10.0"
# Kubernetes Credentials Provider (Jenkins-Version: 2.361.4)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "1.225.v14f9e6b_28f53"
# Lockable Resources (Jenkins-Version: 2.387.3)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "1185.v0c528656ce04"
# Mailer (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "463.vedf8358e006b_"
# Matrix Project (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "802.v8013b_40c7edc"
# Metrics (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.2.18-442.v02e107157925"
# Mina SSHD API :: Common (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins.mina-sshd-api"
    artifactId: "mina-sshd-api-common"
    source:
      version: "2.10.0-69.v28e3e36d18eb_"
# Mina SSHD API :: Core (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins.mina-sshd-api"
    artifactId: "mina-sshd-api-core"
    source:
      version: "2.10.0-69.v28e3e36d18eb_"
# OkHttp (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "4.11.0-157.v6852a_a_fa_ec11"
# Pipeline: Build Step (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "505.v5f0844d8d126"
# Pipeline: GitHub (Jenkins-Version: 2.375.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.8-147.3206e8179b1c"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "42.v0739460cda_c4"
# Pipeline: Groovy Libraries (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-groovy-lib"
    source:
      version: "671.v07c339c842e8"
# Pipeline: Input Step (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "477.v339683a_8d55e"
# Pipeline: Milestone Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "111.v449306f708b_7"
# Pipeline: Model API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "2.2144.v077a_d1928a_40"
# Pipeline: Declarative (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "2.2144.v077a_d1928a_40"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "2.2144.v077a_d1928a_40"
# Pipeline: Stage Step (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "305.ve96d0205c1c6"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "2.2144.v077a_d1928a_40"
# Pipeline Utility Steps (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.16.0"
# Plain Credentials (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "143.v1b_df8b_d3b_e48"
# Plugin Utilities API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "3.3.0"
# Prism API (Jenkins-Version: 2.387.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "prism-api"
    source:
      version: "1.29.0-7"
# Resource Disposer (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.23"
# SCM API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "676.v886669a_199a_a_"
# Script Security (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1264.vecf66020eb_7d"
# SnakeYAML API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "1.33-95.va_b_a_e3e47b_fa_4"
# SSH Credentials (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "308.ve4497b_ccd8f4"
# Structs (Jenkins-Version: 2.289.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "324.va_f5d6774f3a_d"
# Timestamper (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.26"
# Token Macro (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "383.v36161104b_002"
# Trilead API (Jenkins-Version: 2.361)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "2.84.v72119de229b_7"
# Variant (Jenkins-Version: 2.319.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "59.vf075fe829ccb"
# Warnings Next Generation (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "10.4.0"
# Pipeline (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "596.v8c21c963d92d"
# Pipeline: API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "1251.vd4889a_b_0a_065"
# Pipeline: Basic Steps (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "1042.ve7b_140c4a_e0c"
# Pipeline: Groovy (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "3731.ve4b_5b_857b_a_d3"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "1278.v94b_dc2b_50c6f"
# Pipeline: Job (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "1316.vd2290d3341a_f"
# Pipeline: Multibranch (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "756.v891d88f2cd46"
# Pipeline: SCM Step (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "415.v434365564324"
# Pipeline: Step API (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "639.v6eca_cd8c04a_a_"
# Pipeline: Supporting APIs (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "848.v5a_383b_d14921"
# Workspace Cleanup (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.45"
##PLUGINS-END (do not remove!)
