bundle:
  groupId: "com.sap.steward"
  artifactId: "jenkinsfile-runner"
  vendor: "SAP SE"
  title: "Jenkinsfile Runner for Steward"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"

buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "com.sap.steward"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner
        commit: "1.0-beta-32"
    docker:
      base: "jenkins/jenkins:2.426.3-alpine"
      tag: "jenkinsfile-runner-base-local"
      build: true

war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    # In order to avoid severe backwards compatibility issues,
    # keep the Jenkins core version in sync with the used one
    # in the chosen jenkinsfile-runner release
    version: "2.426.3"

systemProperties:
    jenkins.model.Jenkins.slaveAgentPort: "50000"
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"

casc:
  - id: "jcasc"
    source:
      dir: casc.yml

groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy

plugins:

# Special Plugins (not contained on Jenkins UpdateSite)

  # Used to write pipeline logs to Elasticsearch
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-elasticsearch-logs"
    source:
      git: "https://github.com/SAP/elasticsearch-logs-plugin.git"
      commit: "0.14.2"


# See plugins.txt for plugin selection without dependencies (keep this list in sync)
# See README.md for options to generate the list below.

##PLUGINS-START (do not remove!)
# Analysis Model API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "analysis-model-api"
    source:
      version: "11.15.0"
# OWASP Markup Formatter (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "antisamy-markup-formatter"
    source:
      version: "162.v0e6ec0fcfcf6"
# Apache HttpComponents Client 4.x API (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.14-208.v438351942757"
# Authentication Tokens API (Jenkins-Version: 2.387.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "authentication-tokens"
    source:
      version: "1.53.v1c90fd9191a_b_"
# Bootstrap 5 API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "bootstrap5-api"
    source:
      version: "5.3.2-3"
# bouncycastle API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "bouncycastle-api"
    source:
      version: "2.30.1.77-225.v26ea_c9455fd9"
# Branch API (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "branch-api"
    source:
      version: "2.1144.v1425d1c3d5a_7"
# Build Timeout (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "build-timeout"
    source:
      version: "1.32"
# Caffeine API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "caffeine-api"
    source:
      version: "3.1.8-133.v17b_1ff2e0599"
# Checks API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "checks-api"
    source:
      version: "2.0.2"
# Folders (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: "6.858.v898218f3609d"
# Cobertura (Jenkins-Version: 2.204.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cobertura"
    source:
      version: "1.17"
# Code Coverage (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "code-coverage-api"
    source:
      version: "4.99.0"
# commons-lang3 v3.x Jenkins API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-lang3-api"
    source:
      version: "3.13.0-62.v7d18e55f51e2"
# commons-text API (Jenkins-Version: 2.401.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "commons-text-api"
    source:
      version: "1.11.0-95.v22a_d30ee5d36"
# Configuration as Code (Jenkins-Version: 2.414.1)
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1775.v810dc950b_514"
# Configuration as Code Plugin - Groovy Scripting Extension (Jenkins-Version: 2.60.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "configuration-as-code-groovy"
    source:
      version: "1.1"
# Coverage (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "coverage"
    source:
      version: "1.10.0"
# Credentials (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: "1319.v7eb_51b_3a_c97b_"
# Credentials Binding (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: "657.v2b_19db_7d6e6d"
# Cucumber json test reporting (Jenkins-Version: 1.651)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cucumber-testresult-plugin"
    source:
      version: "0.10.1"
# DataTables.net API (Jenkins-Version: 2.426.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "data-tables-api"
    source:
      version: "1.13.8-2"
# Display URL API (Jenkins-Version: 2.361.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "display-url-api"
    source:
      version: "2.200.vb_9327d658781"
# Durable Task (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      version: "547.vd1ea_007d100c"
# ECharts API (Jenkins-Version: 2.426.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "echarts-api"
    source:
      version: "5.4.3-2"
# Font Awesome API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "font-awesome-api"
    source:
      version: "6.5.1-2"
# Forensics API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "forensics-api"
    source:
      version: "2.3.0"
# Gatling (Jenkins-Version: 2.150.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gatling"
    source:
      version: "1.3.0"
# Git (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: "5.2.1"
# Git client (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: "4.6.0"
# GitHub (Jenkins-Version: 2.387.3)
  - groupId: "com.coravy.hudson.plugins.github"
    artifactId: "github"
    source:
      version: "1.37.3.1"
# GitHub API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-api"
    source:
      version: "1.318-461.v7a_c09c9fa_d63"
# GitHub Branch Source (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "github-branch-source"
    source:
      version: "1772.va_69eda_d018d4"
# Gradle (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "gradle"
    source:
      version: "2.9"
# Gson API (Jenkins-Version: 2.401.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "gson-api"
    source:
      version: "2.10.1-15.v0d99f670e0a_7"
# HTML Publisher (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "htmlpublisher"
    source:
      version: "1.32"
# HTTP Request (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "http_request"
    source:
      version: "1.18"
# InfluxDB (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "influxdb"
    source:
      version: "3.6"
# Instance Identity (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.modules"
    artifactId: "instance-identity"
    source:
      version: "185.v303dc7c645f9"
# Ionicons API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "ionicons-api"
    source:
      version: "56.v1b_1c8c49374e"
# Jackson 2 API (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: "2.16.1-373.ve709c6871598"
# JaCoCo (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jacoco"
    source:
      version: "3.3.5"
# Jakarta Activation API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-activation-api"
    source:
      version: "2.0.1-3"
# Jakarta Mail API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "jakarta-mail-api"
    source:
      version: "2.0.1-3"
# JavaBeans Activation Framework (JAF) API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "javax-activation-api"
    source:
      version: "1.2.0-6"
# JAXB (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "jaxb"
    source:
      version: "2.3.9-1"
# Java JSON Web Token (JJWT) (Jenkins-Version: 2.289.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "jjwt-api"
    source:
      version: "0.11.5-77.v646c772fddb_0"
# Joda Time API (Jenkins-Version: 2.401.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "joda-time-api"
    source:
      version: "2.12.6-21.vca_fd74418fb_7"
# JQuery3 API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "jquery3-api"
    source:
      version: "3.7.1-1"
# JSON Api (Jenkins-Version: 2.401.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "json-api"
    source:
      version: "20231013-17.v1c97069404b_e"
# JSON Path API (Jenkins-Version: 2.401.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "json-path-api"
    source:
      version: "2.9.0-33.v2527142f2e1d"
# JUnit (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: "1256.v002534a_5f33e"
# Kubernetes (Jenkins-Version: 2.426.1)
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "4186.v1d804571d5d4"
# Kubernetes Client API (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: "6.10.0-240.v57880ce8b_0b_2"
# Kubernetes Credentials (Jenkins-Version: 2.401.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "kubernetes-credentials"
    source:
      version: "0.11"
# Kubernetes Credentials Provider (Jenkins-Version: 2.414.1)
  - groupId: "com.cloudbees.jenkins.plugins"
    artifactId: "kubernetes-credentials-provider"
    source:
      version: "1.258.v95949f923a_a_e"
# Lockable Resources (Jenkins-Version: 2.387.3)
  - groupId: "org.6wind.jenkins"
    artifactId: "lockable-resources"
    source:
      version: "1232.v512d6c434eb_d"
# Mailer (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: "463.vedf8358e006b_"
# Matrix Project (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "822.824.v14451b_c0fd42"
# Metrics (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "metrics"
    source:
      version: "4.2.21-449.v6960d7c54c69"
# Mina SSHD API :: Common (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins.mina-sshd-api"
    artifactId: "mina-sshd-api-common"
    source:
      version: "2.12.0-90.v9f7fb_9fa_3d3b_"
# Mina SSHD API :: Core (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins.mina-sshd-api"
    artifactId: "mina-sshd-api-core"
    source:
      version: "2.12.0-90.v9f7fb_9fa_3d3b_"
# OkHttp (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "okhttp-api"
    source:
      version: "4.11.0-172.vda_da_1feeb_c6e"
# Pipeline: Build Step (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-build-step"
    source:
      version: "540.vb_e8849e1a_b_d8"
# Pipeline: GitHub (Jenkins-Version: 2.375.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github"
    source:
      version: "2.8-159.09e4403bc62f"
# Pipeline: GitHub Groovy Libraries (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-github-lib"
    source:
      version: "42.v0739460cda_c4"
# Pipeline: Groovy Libraries (Jenkins-Version: 2.414.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-groovy-lib"
    source:
      version: "704.vc58b_8890a_384"
# Pipeline: Input Step (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-input-step"
    source:
      version: "477.v339683a_8d55e"
# Pipeline: Milestone Step (Jenkins-Version: 2.289.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-milestone-step"
    source:
      version: "111.v449306f708b_7"
# Pipeline: Model API (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: "2.2175.v76a_fff0a_2618"
# Pipeline: Declarative (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: "2.2175.v76a_fff0a_2618"
# Pipeline: Declarative Extension Points API (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: "2.2175.v76a_fff0a_2618"
# Pipeline: Stage Step (Jenkins-Version: 2.346.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-stage-step"
    source:
      version: "305.ve96d0205c1c6"
# Pipeline: Stage Tags Metadata (Jenkins-Version: 2.426.1)
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-stage-tags-metadata"
    source:
      version: "2.2175.v76a_fff0a_2618"
# Pipeline Utility Steps (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.16.1"
# Plain Credentials (Jenkins-Version: 2.319.1)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "plain-credentials"
    source:
      version: "143.v1b_df8b_d3b_e48"
# Plugin Utilities API (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "plugin-util-api"
    source:
      version: "3.8.0"
# Prism API (Jenkins-Version: 2.426.1)
  - groupId: "io.jenkins.plugins"
    artifactId: "prism-api"
    source:
      version: "1.29.0-10"
# Resource Disposer (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "resource-disposer"
    source:
      version: "0.23"
# SCM API (Jenkins-Version: 2.426)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: "683.vb_16722fb_b_80b_"
# Script Security (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: "1313.v7a_6067dc7087"
# SnakeYAML API (Jenkins-Version: 2.361.4)
  - groupId: "io.jenkins.plugins"
    artifactId: "snakeyaml-api"
    source:
      version: "2.2-111.vc6598e30cc65"
# SSH Credentials (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ssh-credentials"
    source:
      version: "308.ve4497b_ccd8f4"
# Structs (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: "337.v1b_04ea_4df7c8"
# Timestamper (Jenkins-Version: 2.375.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "timestamper"
    source:
      version: "1.26"
# Token Macro (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "token-macro"
    source:
      version: "400.v35420b_922dcb_"
# Trilead API (Jenkins-Version: 2.401.3)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "trilead-api"
    source:
      version: "2.133.vfb_8a_7b_9c5dd1"
# Variant (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "variant"
    source:
      version: "60.v7290fc0eb_b_cd"
# Warnings (Jenkins-Version: 2.387.3)
  - groupId: "io.jenkins.plugins"
    artifactId: "warnings-ng"
    source:
      version: "10.7.0"
# Pipeline (Jenkins-Version: 2.303.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "596.v8c21c963d92d"
# Pipeline: API (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: "1291.v51fd2a_625da_7"
# Pipeline: Basic Steps (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: "1042.ve7b_140c4a_e0c"
# Pipeline: Groovy (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: "3853.vb_a_490d892963"
# Pipeline: Nodes and Processes (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: "1322.v63864b_7a_e384"
# Pipeline: Job (Jenkins-Version: 2.414)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "1385.vb_58b_86ea_fff1"
# Pipeline: Multibranch (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-multibranch"
    source:
      version: "773.vc4fe1378f1d5"
# Pipeline: SCM Step (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: "415.v434365564324"
# Pipeline: Step API (Jenkins-Version: 2.414.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: "657.v03b_e8115821b_"
# Pipeline: Supporting APIs (Jenkins-Version: 2.387.3)
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: "865.v43e78cc44e0d"
# Workspace Cleanup (Jenkins-Version: 2.361.4)
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "ws-cleanup"
    source:
      version: "0.45"
##PLUGINS-END (do not remove!)
